services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dashboard_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./adapters:/app/adapters
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db/dashboard_db
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8050:8050"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: